### PR TITLE
Add ftw.logo support.

### PR DESCRIPTION
**Pull request by maethu**

### CODE REVIEW

**Comment by maethu** [comment]
> Support for the `marketing` theme is missing

Well, there was no mobile logo anyway. https://github.com/4teamwork/plonetheme.blueberry/blob/master/plonetheme/blueberry/marketing/theme/rules.xml

**Comment by Nachtalb** [comment]
What do you mean there was no logo?
https://github.com/4teamwork/plonetheme.blueberry/blob/35a159a18ffd92b34eaf1b48d90de9ff3d3bd1fa/plonetheme/blueberry/marketing/theme/rules.xml#L15
https://github.com/4teamwork/plonetheme.blueberry/blob/35a159a18ffd92b34eaf1b48d90de9ff3d3bd1fa/plonetheme/blueberry/marketing/theme/index.html#L59

**Comment by maethu** [comment]
> What do you mean there was no logo?
> https://github.com/4teamwork/plonetheme.blueberry/blob/35a159a18ffd92b34eaf1b48d90de9ff3d3bd1fa/plonetheme/blueberry/marketing/theme/rules.xml#L15
> 
> 
> https://github.com/4teamwork/plonetheme.blueberry/blob/35a159a18ffd92b34eaf1b48d90de9ff3d3bd1fa/plonetheme/blueberry/marketing/theme/index.html#L59

no *MOBILE* logo

**Comment by Nachtalb** [comment]
> no _MOBILE_ logo

ahh, stuff like that 
https://github.com/4teamwork/plonetheme.blueberry/blob/6457861b6e438a4f4e5fe5d178fc931d0a2f87e1/plonetheme/blueberry/standard/theme/rules.xml#L43-L46

👍

**Comment by maethu** [comment]
> > no _MOBILE_ logo
> 
> ahh, stuff like that
> https://github.com/4teamwork/plonetheme.blueberry/blob/6457861b6e438a4f4e5fe5d178fc931d0a2f87e1/plonetheme/blueberry/standard/theme/rules.xml#L43-L46
> 
> 👍

exactly.

**Pull request merged**
