### PR TITLE
Define styles for form elements based on ftw.theming.

### PR DESCRIPTION
**Pull request by bierik**
bildschirmfoto 2016-02-08 um 10 43 48
bildschirmfoto 2016-02-08 um 10 43 59
bildschirmfoto 2016-02-08 um 10 44 08
bildschirmfoto 2016-02-08 um 10 45 59

### CODE REVIEW

**Comment by jone** [comment]
I propose to move the "required"-marker to the right side of the label in order to have a consistent vertical alignment of labels:
84a75586-ce51-11e5-86b9-086e439b2ad7

**Comment by bierik** [comment]
@jone updated

bildschirmfoto 2016-02-09 um 10 12 46

**Comment by jone** [comment]
Nice, I like it much better :wink: 
Shall we merge?

**Comment by bierik** [comment]
I think so since we updated ftw.theming. Or should I make a PR on the pu branch?

**Comment by jone** [comment]
Lets put in in a `pu`-branch. Can you make a new pull request?

**Comment by bierik** [comment]
Moved to https://github.com/4teamwork/plonetheme.blueberry/pull/18

**Pull request closed without merging**
